name: A Python Script

on: push

jobs:
  check-format-zhh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: (Look At Here) Run Python Script
        run: |
          python3 .github/scripts/hook.py